# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.box_version = "1.0.282"
# Desconecta el puerto serie por https://www.virtualbox.org/ticket/18319
  config.vm.provider "virtualbox" do |vb|
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected"]
  end
  config.vm.provision "ansible", run: 'always', type: :ansible_local do |ansible| 
    ansible.galaxy_role_file = 'requirements.yml'
    ansible.playbook="configure-app.yml" 
  end
  config.vm.network "forwarded_port", guest: 8080, host: 8080
end
